version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      - rabbitmq_network
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  app1:
    build: ./app1
    ports:
      - "3040:3040"
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

  app2:
    build: ./app2
    ports:
      - "3060:3060"
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

  app3:
    build: ./app3
    ports:
      - "3070:3070"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - rabbitmq_network

  redis:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
